version: "3"
services:
    database:
        image: postgres:alpine
        container_name: postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: owntracks-recorder
            POSTGRES_DB: owntracks
        ports:
            - 5432:5432

volumes:
    postgres:
